### ISSUE TITLE
Add square root kernels

### ISSUE THREAD

**Issue by qh681248** [gchq/coreax#868] opened 2024-11-15 10:21 UTC
### What's the new feature?

See Section2.2 Definition 5 (https://arxiv.org/abs/2105.05842), for Squared Exponential, Matern, beta-spline and a few other kernels, exact square-root kernel is known (See section 2.2, table 1). For other kernels, a square root dominating Matern kernel is known (See Appendix Q, table 5). Add these as a method on existing kernels.

### What value does this add?

Allows user to use Kernel Thinning algorithm as intended by the paper.

**Comment by rg936672** [comment] 2024-11-26 09:27
Closing as duplicate of #867

**Closed by rg936672** 2024-11-26 09:27 UTC
Labels: enhancement, new
